services:
  db-migrations:
    image: ghcr.io/15ajohnson/wedding:latest
    command: ["npx", "prisma", "migrate", "deploy"]
    restart: "no"
    environment:
      DATABASE_URL: file:/data/rsvp.db
    volumes:
      - rsvp-data:/data

  app:
    image: ghcr.io/15ajohnson/wedding:latest
    environment:
      DATABASE_URL: file:/data/rsvp.db
      NEXT_PUBLIC_COMING_SOON: "true"
    volumes:
      - rsvp-data:/data
    ports:
      - "3002:3002"

volumes:
  rsvp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/app-data/collin-alivia-wedding
